# language type:
language: cpp

# compilator system:
compiler:
  - clang
  - gcc

os:
  - linux
  - osx

before_script:
  - cd ..
  - git clone https://github.com/atria-soft/etk.git
  - git clone https://github.com/atria-soft/exml.git
  - git clone https://github.com/atria-soft/libagg.git
  - git clone https://github.com/generic-library/gtest-lutin.git --recursive
  - git clone https://github.com/generic-library/freetype-lutin.git --recursive
  - pwd
  - ls -l
  - if [ "$CXX" == "clang++" ]; then BUILDER=clang; else BUILDER=gcc; fi

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9
  - sudo apt-get install -qq libstdc++-4.9-dev
  - sudo rm /usr/bin/gcc /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
  - sudo pip install lutin

# build sequence with Lutin :
script: 
  - lutin -C -P -c$BUILDER -mdebug -p esvg

#send e-mail on compilation result:
notifications:
  email:
    - yui.heero@gmail.com

